# LAB7 Assignment
> The document description are designed by JIa Yanhong in 2022. Oct. 20th
------

## LAB Assignment
### Exercise 1 logistic regression (20 points )
This exercise uses dataset digit01.csv , which has 13 columns, and the last column is the dependent variable. 

This part requires you to implement a `logistic regression` using the pytorch framework (defining a logistic regression class that inherits `nn.module`). To test your model, we provide a dataset `digit01.csv` which is in the **datasets folder**. This dataset requires you to divide the training set and the test set by yourself, and it is recommended that 80% of the training set and 20% of the test set be used.

In [32]:
import torch

device = torch.device('mps')  # apple silicon gpu
# device = torch.device('cpu')

+ load datasets

In [33]:
import pandas as pd

digit01 = pd.read_csv('datasets/digit01.csv', header=None)
digit01.head()

0   1   2   3   4   5   6   7   8   9   10  11  12
0   1   1   1   1   0   1   1   0   1   1   1   1   0
1   0   1   1   1   0   1   1   0   1   1   1   1   0
2   1   1   0   1   0   1   1   0   1   1   1   1   0
3   1   1   1   1   0   1   1   0   1   1   1   0   0
4   1   1   1   1   0   1   1   0   1   0   1   1   0

+ Splitting dataset into 80% Training and 20% Testing Data:

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digit01.iloc[:, :-1], digit01.iloc[:, -1], test_size=0.2, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((51, 12), (13, 12), (51,), (13,))

In [35]:
from torch import from_numpy

X_train = from_numpy(X_train.values).float().to(device)
y_train = from_numpy(y_train.values).long().to(device)
X_test = from_numpy(X_test.values).float().to(device)
y_test = from_numpy(y_test.values).long().to(device)

In [36]:
X_train

tensor([[1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
        [1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0.],
        [1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.],
        [0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
        [0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1.],
        [1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
        [1., 1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1.],
        [1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
        [1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 1.],
        [0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0.],
        [1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.],
        [1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1.],
        [1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1.],
        [0., 0

+ Define a LogisticRegression subclass of nn. Module

In [37]:
from torch import nn

class LogisticRegression(nn.Module):
    def __init__(self, i_dim, o_dim):
        super(LogisticRegression, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(i_dim, o_dim),
            nn.Sigmoid(),
        )

    def forward(self, x):
        return self.model.forward(x)

+ Create the model

In [38]:
logistic_reg = LogisticRegression(X_train.shape[1], 2).to(device)
logistic_reg.requires_grad_()

LogisticRegression(
  (model): Sequential(
    (0): Linear(in_features=12, out_features=2, bias=True)
    (1): Sigmoid()
  )
)

 + Loss function

In [39]:
# loss_func = nn.MSELoss(reduction='sum')
loss_func = nn.CrossEntropyLoss()

+ The optimizer

In [40]:
from torch import optim

# optimizer = optim.RMSprop(params=logistic_reg.parameters(), lr=1e-3)
optimizer = optim.SGD(logistic_reg.parameters(), lr=1e-3)

+ training Model

In [41]:
from tqdm import tqdm

train_proc = tqdm(range(10000))
for t in train_proc:
    logistic_reg.train()
    optimizer.zero_grad()

    y_pred = logistic_reg(X_train)
    print(y_pred)
    print(y_train)
    loss = loss_func(y_pred, y_train)
    train_proc.set_description('loss: %.4f' % loss.item())

    loss.backward()
    optimizer.step()

loss: 0.7409:   0%|          | 3/10000 [00:00<07:42, 21.63it/s]

tensor([[0.4874, 0.4009],
        [0.5266, 0.4467],
        [0.4765, 0.3974],
        [0.3579, 0.4012],
        [0.3618, 0.4731],
        [0.3545, 0.4117],
        [0.3404, 0.4806],
        [0.3364, 0.5384],
        [0.5335, 0.4001],
        [0.3278, 0.4457],
        [0.3536, 0.4213],
        [0.2559, 0.4452],
        [0.5261, 0.4938],
        [0.4609, 0.4290],
        [0.5025, 0.4039],
        [0.3466, 0.5154],
        [0.2500, 0.5025],
        [0.4675, 0.4601],
        [0.4956, 0.4506],
        [0.2779, 0.4591],
        [0.3466, 0.5278],
        [0.3475, 0.5056],
        [0.3213, 0.5404],
        [0.4373, 0.5112],
        [0.4155, 0.4298],
        [0.5266, 0.4467],
        [0.4719, 0.4847],
        [0.4332, 0.4384],
        [0.5055, 0.4093],
        [0.3204, 0.5502],
        [0.4678, 0.3829],
        [0.5335, 0.4001],
        [0.2977, 0.5028],
        [0.2723, 0.5068],
        [0.2969, 0.5126],
        [0.3683, 0.4884],
        [0.4442, 0.4635],
        [0.4986, 0.4562],
        [0.3

loss: 0.7407:   0%|          | 9/10000 [00:00<07:34, 21.96it/s]

tensor([[0.4876, 0.4007],
        [0.5265, 0.4468],
        [0.4765, 0.3975],
        [0.3581, 0.4009],
        [0.3621, 0.4727],
        [0.3545, 0.4116],
        [0.3405, 0.4804],
        [0.3365, 0.5382],
        [0.5334, 0.4002],
        [0.3280, 0.4453],
        [0.3536, 0.4212],
        [0.2561, 0.4448],
        [0.5261, 0.4938],
        [0.4608, 0.4290],
        [0.5024, 0.4040],
        [0.3468, 0.5151],
        [0.2501, 0.5023],
        [0.4674, 0.4602],
        [0.4954, 0.4508],
        [0.2781, 0.4587],
        [0.3468, 0.5275],
        [0.3477, 0.5052],
        [0.3216, 0.5400],
        [0.4373, 0.5112],
        [0.4157, 0.4295],
        [0.5265, 0.4468],
        [0.4719, 0.4847],
        [0.4331, 0.4384],
        [0.5054, 0.4093],
        [0.3207, 0.5498],
        [0.4677, 0.3830],
        [0.5334, 0.4002],
        [0.2979, 0.5024],
        [0.2726, 0.5064],
        [0.2971, 0.5123],
        [0.3684, 0.4883],
        [0.4441, 0.4635],
        [0.4984, 0.4562],
        [0.3

loss: 0.7405:   0%|          | 15/10000 [00:00<07:12, 23.09it/s]

tensor([[0.4878, 0.4004],
        [0.5264, 0.4469],
        [0.4764, 0.3975],
        [0.3584, 0.4005],
        [0.3623, 0.4723],
        [0.3546, 0.4115],
        [0.3407, 0.4802],
        [0.3367, 0.5380],
        [0.5333, 0.4003],
        [0.3283, 0.4450],
        [0.3536, 0.4212],
        [0.2563, 0.4445],
        [0.5260, 0.4939],
        [0.4607, 0.4291],
        [0.5022, 0.4041],
        [0.3470, 0.5148],
        [0.2503, 0.5020],
        [0.4673, 0.4602],
        [0.4953, 0.4509],
        [0.2784, 0.4583],
        [0.3470, 0.5272],
        [0.3480, 0.5049],
        [0.3219, 0.5396],
        [0.4372, 0.5112],
        [0.4159, 0.4293],
        [0.5264, 0.4469],
        [0.4718, 0.4847],
        [0.4330, 0.4384],
        [0.5053, 0.4094],
        [0.3210, 0.5494],
        [0.4676, 0.3830],
        [0.5333, 0.4003],
        [0.2982, 0.5020],
        [0.2728, 0.5060],
        [0.2973, 0.5119],
        [0.3684, 0.4882],
        [0.4441, 0.4635],
        [0.4983, 0.4563],
        [0.3

loss: 0.7404:   0%|          | 18/10000 [00:00<07:11, 23.12it/s]

tensor([[0.4879, 0.4002],
        [0.5262, 0.4471],
        [0.4763, 0.3975],
        [0.3587, 0.4002],
        [0.3626, 0.4720],
        [0.3546, 0.4114],
        [0.3409, 0.4799],
        [0.3368, 0.5378],
        [0.5331, 0.4004],
        [0.3285, 0.4446],
        [0.3536, 0.4211],
        [0.2565, 0.4441],
        [0.5259, 0.4939],
        [0.4606, 0.4292],
        [0.5021, 0.4042],
        [0.3472, 0.5145],
        [0.2505, 0.5017],
        [0.4672, 0.4603],
        [0.4952, 0.4510],
        [0.2787, 0.4578],
        [0.3472, 0.5269],
        [0.3482, 0.5046],
        [0.3222, 0.5392],
        [0.4372, 0.5112],
        [0.4161, 0.4290],
        [0.5262, 0.4471],
        [0.4718, 0.4847],
        [0.4330, 0.4384],
        [0.5052, 0.4094],
        [0.3212, 0.5491],
        [0.4676, 0.3831],
        [0.5331, 0.4004],
        [0.2985, 0.5016],
        [0.2731, 0.5056],
        [0.2976, 0.5115],
        [0.3685, 0.4881],
        [0.4440, 0.4635],
        [0.4982, 0.4564],
        [0.3

loss: 0.7402:   0%|          | 24/10000 [00:01<07:05, 23.44it/s]

tensor([[0.4881, 0.4000],
        [0.5261, 0.4472],
        [0.4762, 0.3976],
        [0.3589, 0.3998],
        [0.3628, 0.4716],
        [0.3547, 0.4113],
        [0.3410, 0.4797],
        [0.3370, 0.5376],
        [0.5330, 0.4005],
        [0.3288, 0.4443],
        [0.3537, 0.4210],
        [0.2567, 0.4438],
        [0.5258, 0.4940],
        [0.4606, 0.4292],
        [0.5020, 0.4043],
        [0.3474, 0.5142],
        [0.2506, 0.5014],
        [0.4671, 0.4604],
        [0.4950, 0.4511],
        [0.2789, 0.4574],
        [0.3474, 0.5266],
        [0.3484, 0.5043],
        [0.3224, 0.5388],
        [0.4371, 0.5113],
        [0.4163, 0.4288],
        [0.5261, 0.4472],
        [0.4717, 0.4847],
        [0.4329, 0.4384],
        [0.5051, 0.4095],
        [0.3215, 0.5487],
        [0.4675, 0.3831],
        [0.5330, 0.4005],
        [0.2987, 0.5012],
        [0.2734, 0.5052],
        [0.2978, 0.5112],
        [0.3686, 0.4880],
        [0.4440, 0.4635],
        [0.4981, 0.4564],
        [0.3

loss: 0.7400:   0%|          | 30/10000 [00:01<07:22, 22.51it/s]

tensor([[0.4882, 0.3998],
        [0.5259, 0.4473],
        [0.4761, 0.3976],
        [0.3592, 0.3995],
        [0.3631, 0.4713],
        [0.3547, 0.4112],
        [0.3412, 0.4795],
        [0.3371, 0.5373],
        [0.5329, 0.4006],
        [0.3290, 0.4439],
        [0.3537, 0.4210],
        [0.2569, 0.4435],
        [0.5257, 0.4940],
        [0.4605, 0.4293],
        [0.5018, 0.4044],
        [0.3476, 0.5139],
        [0.2508, 0.5011],
        [0.4670, 0.4605],
        [0.4949, 0.4512],
        [0.2792, 0.4570],
        [0.3476, 0.5263],
        [0.3487, 0.5039],
        [0.3227, 0.5384],
        [0.4370, 0.5113],
        [0.4165, 0.4285],
        [0.5259, 0.4473],
        [0.4717, 0.4848],
        [0.4329, 0.4384],
        [0.5050, 0.4095],
        [0.3218, 0.5483],
        [0.4674, 0.3831],
        [0.5329, 0.4006],
        [0.2990, 0.5008],
        [0.2736, 0.5048],
        [0.2981, 0.5108],
        [0.3686, 0.4879],
        [0.4439, 0.4635],
        [0.4980, 0.4565],
        [0.3

loss: 0.7398:   0%|          | 33/10000 [00:01<07:22, 22.51it/s]

tensor([[0.4884, 0.3996],
        [0.5258, 0.4474],
        [0.4761, 0.3976],
        [0.3594, 0.3991],
        [0.3634, 0.4709],
        [0.3547, 0.4111],
        [0.3413, 0.4792],
        [0.3373, 0.5371],
        [0.5327, 0.4007],
        [0.3293, 0.4435],
        [0.3537, 0.4209],
        [0.2571, 0.4431],
        [0.5256, 0.4941],
        [0.4604, 0.4293],
        [0.5017, 0.4045],
        [0.3478, 0.5136],
        [0.2510, 0.5008],
        [0.4669, 0.4605],
        [0.4947, 0.4513],
        [0.2795, 0.4566],
        [0.3478, 0.5260],
        [0.3489, 0.5036],
        [0.3230, 0.5380],
        [0.4370, 0.5113],
        [0.4167, 0.4283],
        [0.5258, 0.4474],
        [0.4717, 0.4848],
        [0.4328, 0.4385],
        [0.5049, 0.4096],
        [0.3220, 0.5480],
        [0.4673, 0.3832],
        [0.5327, 0.4007],
        [0.2993, 0.5004],
        [0.2739, 0.5044],
        [0.2983, 0.5105],
        [0.3687, 0.4877],
        [0.4439, 0.4635],
        [0.4979, 0.4566],
        [0.3

loss: 0.7397:   0%|          | 39/10000 [00:01<07:24, 22.39it/s]

tensor([[0.4886, 0.3994],
        [0.5256, 0.4475],
        [0.4760, 0.3977],
        [0.3597, 0.3988],
        [0.3636, 0.4706],
        [0.3548, 0.4110],
        [0.3415, 0.4790],
        [0.3374, 0.5369],
        [0.5326, 0.4008],
        [0.3296, 0.4432],
        [0.3537, 0.4208],
        [0.2574, 0.4428],
        [0.5255, 0.4942],
        [0.4603, 0.4294],
        [0.5016, 0.4046],
        [0.3480, 0.5133],
        [0.2511, 0.5005],
        [0.4668, 0.4606],
        [0.4946, 0.4514],
        [0.2797, 0.4562],
        [0.3480, 0.5257],
        [0.3491, 0.5033],
        [0.3233, 0.5376],
        [0.4369, 0.5113],
        [0.4169, 0.4280],
        [0.5256, 0.4475],
        [0.4716, 0.4848],
        [0.4327, 0.4385],
        [0.5048, 0.4097],
        [0.3223, 0.5476],
        [0.4672, 0.3832],
        [0.5326, 0.4008],
        [0.2995, 0.5000],
        [0.2741, 0.5040],
        [0.2985, 0.5101],
        [0.3688, 0.4876],
        [0.4438, 0.4635],
        [0.4978, 0.4567],
        [0.3

loss: 0.7395:   0%|          | 45/10000 [00:01<07:18, 22.68it/s]

tensor([[0.4887, 0.3992],
        [0.5255, 0.4476],
        [0.4759, 0.3977],
        [0.3600, 0.3984],
        [0.3639, 0.4702],
        [0.3548, 0.4109],
        [0.3417, 0.4787],
        [0.3376, 0.5367],
        [0.5325, 0.4009],
        [0.3298, 0.4428],
        [0.3537, 0.4208],
        [0.2576, 0.4425],
        [0.5255, 0.4942],
        [0.4602, 0.4295],
        [0.5015, 0.4047],
        [0.3483, 0.5130],
        [0.2513, 0.5002],
        [0.4667, 0.4607],
        [0.4945, 0.4516],
        [0.2800, 0.4558],
        [0.3482, 0.5255],
        [0.3494, 0.5029],
        [0.3236, 0.5372],
        [0.4369, 0.5113],
        [0.4171, 0.4278],
        [0.5255, 0.4476],
        [0.4716, 0.4848],
        [0.4327, 0.4385],
        [0.5047, 0.4097],
        [0.3225, 0.5472],
        [0.4671, 0.3833],
        [0.5325, 0.4009],
        [0.2998, 0.4996],
        [0.2744, 0.5036],
        [0.2988, 0.5098],
        [0.3689, 0.4875],
        [0.4438, 0.4635],
        [0.4977, 0.4567],
        [0.3

loss: 0.7393:   0%|          | 48/10000 [00:02<07:23, 22.43it/s]

tensor([[0.4889, 0.3990],
        [0.5254, 0.4477],
        [0.4758, 0.3977],
        [0.3602, 0.3981],
        [0.3642, 0.4699],
        [0.3549, 0.4108],
        [0.3418, 0.4785],
        [0.3377, 0.5365],
        [0.5323, 0.4010],
        [0.3301, 0.4424],
        [0.3537, 0.4207],
        [0.2578, 0.4421],
        [0.5254, 0.4943],
        [0.4601, 0.4295],
        [0.5013, 0.4048],
        [0.3485, 0.5127],
        [0.2515, 0.4999],
        [0.4666, 0.4607],
        [0.4943, 0.4517],
        [0.2803, 0.4554],
        [0.3484, 0.5252],
        [0.3496, 0.5026],
        [0.3239, 0.5368],
        [0.4368, 0.5114],
        [0.4173, 0.4275],
        [0.5254, 0.4477],
        [0.4715, 0.4848],
        [0.4326, 0.4385],
        [0.5046, 0.4098],
        [0.3228, 0.5469],
        [0.4670, 0.3833],
        [0.5323, 0.4010],
        [0.3001, 0.4992],
        [0.2747, 0.5032],
        [0.2990, 0.5094],
        [0.3689, 0.4874],
        [0.4437, 0.4635],
        [0.4976, 0.4568],
        [0.3

loss: 0.7391:   1%|          | 54/10000 [00:02<07:21, 22.54it/s]

tensor([[0.4891, 0.3988],
        [0.5252, 0.4479],
        [0.4758, 0.3978],
        [0.3605, 0.3978],
        [0.3644, 0.4695],
        [0.3549, 0.4107],
        [0.3420, 0.4783],
        [0.3379, 0.5362],
        [0.5322, 0.4011],
        [0.3303, 0.4421],
        [0.3537, 0.4206],
        [0.2580, 0.4418],
        [0.5253, 0.4943],
        [0.4600, 0.4296],
        [0.5012, 0.4049],
        [0.3487, 0.5124],
        [0.2516, 0.4996],
        [0.4665, 0.4608],
        [0.4942, 0.4518],
        [0.2805, 0.4550],
        [0.3487, 0.5249],
        [0.3499, 0.5023],
        [0.3242, 0.5364],
        [0.4367, 0.5114],
        [0.4175, 0.4273],
        [0.5252, 0.4479],
        [0.4715, 0.4848],
        [0.4326, 0.4385],
        [0.5045, 0.4098],
        [0.3231, 0.5465],
        [0.4670, 0.3834],
        [0.5322, 0.4011],
        [0.3003, 0.4989],
        [0.2749, 0.5028],
        [0.2992, 0.5090],
        [0.3690, 0.4873],
        [0.4436, 0.4635],
        [0.4975, 0.4569],
        [0.3

loss: 0.7390:   1%|          | 58/10000 [00:02<07:22, 22.48it/s]

tensor([[0.4892, 0.3986],
        [0.5251, 0.4480],
        [0.4757, 0.3978],
        [0.3608, 0.3974],
        [0.3647, 0.4692],
        [0.3550, 0.4106],
        [0.3421, 0.4780],
        [0.3380, 0.5360],
        [0.5321, 0.4012],
        [0.3306, 0.4417],
        [0.3537, 0.4206],
        [0.2582, 0.4415],
        [0.5252, 0.4944],
        [0.4599, 0.4297],
        [0.5011, 0.4050],
        [0.3489, 0.5122],
        [0.2518, 0.4994],
        [0.4664, 0.4609],
        [0.4941, 0.4519],
        [0.2808, 0.4546],
        [0.3489, 0.5246],
        [0.3501, 0.5019],
        [0.3245, 0.5360],
        [0.4367, 0.5114],
        [0.4177, 0.4270],
        [0.5251, 0.4480],
        [0.4714, 0.4848],
        [0.4325, 0.4385],
        [0.5044, 0.4099],
        [0.3233, 0.5461],
        [0.4669, 0.3834],
        [0.5321, 0.4012],
        [0.3006, 0.4985],
        [0.2752, 0.5024],
        [0.2995, 0.5087],
        [0.3691, 0.4872],
        [0.4436, 0.4635],
        [0.4974, 0.4569],
        [0.3

KeyboardInterrupt: 


+ Model Performance


In [ ]:
import torch

with torch.no_grad():
    logits = logistic_reg(X_test)
    y_pred = nn.Softmax(dim=1)(logits)
    y_predicted_cls = y_pred.argmax(1)
    acc = y_predicted_cls.eq(y_test).sum() / float(y_test.shape[0])
    print(f'accuracy: {acc.item():.4f}')

accuracy: 1.0000


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test.cpu(), y_predicted_cls.cpu()))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         7

    accuracy                           1.00        13
   macro avg       1.00      1.00      1.00        13
weighted avg       1.00      1.00      1.00        13



### Exercise 2  Handwriting recognition with MLP

Like last week's lab , your task in this section is also about recognizing handwritten digits, but you are required to use MLP to complete the exercise. It is recommended that you define an MLP class, which is a subclass of `nn.module`.

<font color='red' size=4>Note that your accuracy in this section will directly determine your score.</font>

For this exercise we use the `minist` dataset.

+ load datasets

In [ ]:
import struct
import numpy as np
from array import array

def read_images_labels(images_filepath, labels_filepath):        
    labels, images = [], []

    with open(labels_filepath, 'rb') as file:
        magic, size = struct.unpack('>II', file.read(8))
        assert magic == 2049
        labels = array('B', file.read())        

    with open(images_filepath, 'rb') as file:
        magic, size, rows, cols = struct.unpack('>IIII', file.read(16))
        assert magic == 2051
        image_data = array('B', file.read())

    for i in range(size):
        images.append([0] * rows * cols)
    for i in range(size):
        img = np.array(image_data[i * rows * cols:(i + 1) * rows * cols])
        images[i][:] = img

    return np.array(images), np.array(labels)

In [ ]:
X_train, y_train = read_images_labels('datasets/MNIST/raw/train-images-idx3-ubyte', 'datasets/MNIST/raw/train-labels-idx1-ubyte')
X_test, y_test = read_images_labels('datasets/MNIST/raw/t10k-images-idx3-ubyte', 'datasets/MNIST/raw/t10k-labels-idx1-ubyte')

X_train = from_numpy(np.array(X_train)).float().to('cpu')
y_train = from_numpy(np.array(y_train)).long().to('cpu')
X_test = from_numpy(np.array(X_test)).float().to('cpu')
y_test = from_numpy(np.array(y_test)).long().to('cpu')

+ Define a MLP subclass of nn. Module

In [ ]:
from torch import nn

class MLP(nn.Module):
    def __init__(self, n_i, n_h, n_o):
        super(MLP, self).__init__()
        self.model = nn.Sequential(
            nn.Flatten(),
            nn.Linear(n_i, n_h),
            nn.ReLU(),
            nn.Linear(n_h, n_o),
        )

    def forward(self, x):
        return self.model.forward(x)

+ Create the model

In [ ]:
mlp = MLP(X_train.shape[1], X_train.shape[1]//2, y_train.unique().size()[0]).to('cpu')
mlp.requires_grad_()

MLP(
  (model): Sequential(
    (0): Flatten(start_dim=1, end_dim=-1)
    (1): Linear(in_features=784, out_features=392, bias=True)
    (2): ReLU()
    (3): Linear(in_features=392, out_features=10, bias=True)
  )
)

 + Loss function

In [ ]:
criterions = nn.CrossEntropyLoss()

+ The optimizer

In [ ]:
optimizer = optim.SGD(mlp.parameters(), lr=1e-3)

+ training Model

In [ ]:
train_proc = tqdm(range(10000))

for t in train_proc:
    mlp.train()
    optimizer.zero_grad()

    y_pred = mlp(X_train)
    loss = criterions(y_pred, y_train)
    train_proc.set_description('loss: %.4f' % loss.item())

    loss.backward()
    optimizer.step()

loss: 0.0306:  31%|███       | 3108/10000 [04:55<10:55, 10.52it/s]


KeyboardInterrupt: 

+ Model Performance

In [ ]:
with torch.no_grad():
    logits = mlp(X_test)
    y_pred = nn.Softmax(dim=1)(logits)
    y_predicted_cls = y_pred.argmax(1)
    acc = y_predicted_cls.eq(y_test).sum() / float(y_test.shape[0])
    print(f'accuracy: {acc.item():.10f}')

accuracy: 0.9575999975


In [ ]:
# classification report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predicted_cls))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       980
           1       0.98      0.99      0.98      1135
           2       0.96      0.96      0.96      1032
           3       0.95      0.95      0.95      1010
           4       0.96      0.96      0.96       982
           5       0.95      0.93      0.94       892
           6       0.96      0.96      0.96       958
           7       0.96      0.96      0.96      1028
           8       0.93      0.94      0.94       974
           9       0.94      0.94      0.94      1009

    accuracy                           0.96     10000
   macro avg       0.96      0.96      0.96     10000
weighted avg       0.96      0.96      0.96     10000



### Exercise 3  Questions (10 points )
1.What's the difference between logistic regression and Perceptron?

- Logistic regression uses a logistic function, while perceptron uses a step function. Therefore the output of logistic regression is continuous, while the output of perceptron is discrete.
- The parameter vector for the perceptron may be arbitrarily scaled compared to the one derived by logistic regression. Any scaling of the parameter vector will define the same boundary, but the probabilities calculated by logistic regression depend on the exact scaling.
> ref: [stackoverflow](https://stats.stackexchange.com/questions/162257/whats-the-difference-between-logistic-regression-and-perceptron)

2.Advantages and disadvantages of neural networks?

- Advantages
  - it can learn continuously, for specific users/tasks, the performance can be improved over time
  - easy to use, no need to manually design features
- Disadvantages
  - it's interpretation is low, say, hard to explain the reason why the model makes a decision
  - easy to overfit
  - requires a large dataset to train

3.What is the role of Activation Function in Neural networks?

It's the import role that makes the NN to be non-linear, and thus the system could be more powerful. 
It also decides whether a neuron should be activated or not.